<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hcs_bringup</name>
  <version>1.0.0</version>
  <description>Launch files and per-robot configs for HCS</description>
  <maintainer email="zyi024424@gmail.com">zyi</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hcs_base</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>hcs_executor</exec_depend>
  <exec_depend>hcs_core</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
