<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hcs_demo</name>
  <version>1.0.0</version>
  <description>Minimal runnable example components for the HCS executor framework</description>
  <maintainer email="zyi024424@gmail.com">zyi</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>hcs_executor</depend>
  <depend>hcs_sync</depend>
  <depend>hcs_utility</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
